import os

os.makedirs('rag', exist_ok=True)
with open('rag/__init__.py', 'w') as f: f.write('')

with open('services/llm_service.py', 'w') as f:
    f.write('''import os

class LLMService:
    def __init__(self):
        self.enabled = os.getenv("LLM_ENABLED", "false").lower() == "true"
        self.model = os.getenv("OLLAMA_MODEL", "llama2")

    def generate(self, prompt, context):
        if not self.enabled:
            return None
        return "This is a response generated by the local LLM."
''')

with open('services/chatbot_service.py', 'w') as f:
    f.write('''import json
from pathlib import Path
from .nlp_service import NLPService
from .safety_service import SafetyService
from .llm_service import LLMService

class ChatbotService:
    def __init__(self):
        self.nlp = NLPService()
        self.safety = SafetyService()
        self.llm = LLMService()
        path = Path(__file__).resolve().parent.parent / "data" / "health_topics.json"
        self.topics = json.loads(path.read_text(encoding="utf-8"))

    def respond(self, message):
        if self.safety.is_emergency(message):
            return {"intent": "emergency", "urgent": True, "response":
                "This may involve symptoms that require urgent medical attention. "
                "Please contact a qualified healthcare professional or your local emergency "
                "service immediately. In India, you can contact 112 for emergency assistance. "
                "This chatbot cannot assess or diagnose emergencies."}

        intent, confidence = self.nlp.predict(message)
        
        if confidence < 0.45:
            return {"intent": "unknown", "confidence": confidence, "urgent": False, "response": "I couldn't confidently identify the health topic in your question. Please describe your symptoms or question in more detail. If you have severe or concerning symptoms, please consult a qualified healthcare professional."}

        topic = self._find_topic(intent, message)

        if topic:
            response = self._format_topic(topic)
        elif intent == "greeting":
            response = "Hello! I can provide general information about common health topics. What would you like to know?"
        elif intent == "thanks":
            response = "You're welcome. Remember that this chatbot provides general information and is not a substitute for professional medical advice."
        elif intent == "goodbye":
            response = "Take care. If you have concerning or severe symptoms, seek professional medical assistance."
        else:
            response = ("I couldn't confidently match your question. Please describe your symptoms "
                        "or question in more detail. If symptoms are severe or concerning, contact a qualified healthcare professional.")
                        
        llm_resp = self.llm.generate(message, response)
        if llm_resp:
            response = llm_resp

        return {"intent": intent, "confidence": round(float(confidence), 3), "urgent": False, "response": response}

    def _find_topic(self, intent, message):
        text = message.lower()
        for topic in self.topics:
            if topic["intent"] == intent:
                return topic
            if any(k.lower() in text for k in topic.get("keywords", [])):
                return topic
        return None

    def _format_topic(self, t):
        symptoms = "\\n".join(f"• {x}" for x in t.get("common_symptoms", [])) or "• No specific symptom list"
        guidance = "\\n".join(f"• {x}" for x in t.get("general_guidance", []))
        return (f"General information about {t.get('topic')}:\\n\\n{t.get('description')}\\n\\n"
                f"Common symptoms:\\n{symptoms}\\n\\nGeneral guidance:\\n{guidance}\\n\\n"
                f"When to seek medical care:\\n{t.get('seek_medical_help')}\\n\\n"
                "Disclaimer: This information is educational only and is not a medical diagnosis.")
''')

with open('app.py', 'w') as f:
    f.write('''from flask import Flask, render_template, request, jsonify
from services.chatbot_service import ChatbotService

app = Flask(__name__)
app.config["SECRET_KEY"] = "change-this-secret-key"
chatbot = ChatbotService()

@app.route("/")
def index():
    return "Healthcare Bot"

@app.route("/api/chat", methods=["POST"])
def chat():
    data = request.get_json(silent=True) or {}
    message = (data.get("message") or "").strip()
    if not message:
        return jsonify({"error": "Please enter a message."}), 400
    return jsonify(chatbot.respond(message))

if __name__ == "__main__":
    app.run(debug=True)
''')
